version: '3'

services:
  db:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: 'test'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./data/db:/var/lib/postgresql/data
